defmodule ExFinancialModelingPrep.Struct.CashFlowStatement do
  use TypedStruct

  typedstruct do
    field(:purchases_of_investments, Integer.t())
    field(:stock_based_compensation, Integer.t())
    field(:inventory, Integer.t())
    field(:common_stock_issued, float())
    field(:sales_maturities_of_investments, Integer.t())
    field(:accepted_date, String.t())
    field(:period, String.t())
    field(:investments_in_property_plant_and_equipment, Integer.t())
    field(:capital_expenditure, Integer.t())
    field(:other_financing_activites, Integer.t())
    field(:deferred_income_tax, Integer.t())
    field(:dividends_paid, Integer.t())
    field(:net_change_in_cash, Integer.t())
    field(:operating_cash_flow, Integer.t())
    field(:reported_currency, String.t())
    field(:accounts_receivables, Integer.t())
    field(:depreciation_and_amortization, Integer.t())
    field(:symbol, String.t())
    field(:other_investing_activites, Integer.t())
    field(:other_non_cash_items, float())
    field(:effect_of_forex_changes_on_cash, float())
    field(:final_link, String.t())
    field(:net_income, Integer.t())
    field(:cash_at_beginning_of_period, Integer.t())
    field(:change_in_working_capital, Integer.t())
    field(:cash_at_end_of_period, Integer.t())
    field(:filling_date, String.t())
    field(:other_working_capital, float())
    field(:debt_repayment, Integer.t())
    field(:net_cash_provided_by_operating_activities, Integer.t())
    field(:cik, String.t())
    field(:link, String.t())
    field(:calendar_year, String.t())
    field(:net_cash_used_provided_by_financing_activities, Integer.t())
    field(:acquisitions_net, Integer.t())
    field(:net_cash_used_for_investing_activites, Integer.t())
    field(:accounts_payables, Integer.t())
    field(:date, String.t())
    field(:free_cash_flow, Integer.t())
    field(:common_stock_repurchased, Integer.t())
  end
end
